apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
  - name: validate.default.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    rules:
      - apiGroups: ["apps", ""]
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE
    clientConfig:
      service:
        name: validate
        namespace: default
        path: /validate/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVU0c2RXB1YVpGdEFkTHpwQTljdk9mb3RTcXFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNUVXN4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TVRBM01UZ3lNRFUzTURsYUZ3MHlOREExCk1EY3lNRFUzTURsYU1FVXhDekFKQmdOVkJBWVRBazFMTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzJKclp2TGo2d0hvemEvYTdtUzdSTXlIbzZSMng2MHBFYXZyUGRtUjJkCllCd09jSUk0Z3hrVjNKczRnUjR0RzUyTkNRZngvK1hFNmYzTDJ4Y3dzbEJLUWFXVnREYmVvL3BzT1E1Y1hCNFUKcm5DT3VWcmw3Zk95YnVQWERaZUtuNkZMSEk0OW5rTTV2WDBKbFlmSEpGbXdvUlpzMSs5a0JySzJYSm5vUHpUOApNZ0RqRzJmMVhzQ2JIeVdIdko0aVB5bWZmMHEyZW9FZkcyb1JRM3hNcFpxVjZWNlhXamJLWm5yQWVxK0pLbEQzCm9nVzFwVEF4WXRsUUxRbVlqTmJZTE9Pb3hTYmJkQXNBS3M2TzVBMTFTRWxwekMwbnc4RGF5TkJmMjU0VDZ4TGkKY0E1VWdObForbU5GMFphdGNldk93WFRUS1VQMlEydDN5Ry9tV3ZhN0hJK3pBZ01CQUFHamREQnlNQjBHQTFVZApEZ1FXQkJUdkZOYnQ5bjhERjhoTldualBCKyt5Vnp3RzdqQWZCZ05WSFNNRUdEQVdnQlR2Rk5idDluOERGOGhOCldualBCKyt5Vnp3RzdqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01COEdBMVVkRVFRWU1CYUNGSFpoYkdsa1lYUmwKTG1SbFptRjFiSFF1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjBaeXE1U0lRNk0yUGhPMXRya1pZcAptVVh3am90UVZ4NTRLdjZFRjM4eTVHQnNQRlloS2ovRlBMTHN5RE5KTlE2WkdyL2ljbm44VmNaUmg2TXczUUM2CnhXSjFra093a2pobGNGMUs4MUdkNzFOT0djYU5WVE0rM0FDcEx3WEdUbUx4cUo0eWNyVzczMUZYT21pTW9WakkKWlNPakExdkZ5WW9wZXNaaFAycTdXc3ZiVVhFNVFoQ21meFB2NkhyNDZqOE5wNi9wYWcrb1BxdkNDWmgvTm9hLwoyMS82OWFtSzQ4aTNMVmJOcEJLVHAreGlYS0pCOWUzcUIvWkU5RGs5dXkxTzN2V1VUK3RWTjhLZ3ZONXdyMlpDClNIc2FPaEwraUtXeHBtYUJ1QUZFb2FUT2xlQTh2NUp5VGpOSkhqOWtSYTNjejJHZ1lQdUY5VFE3UUYxM2dTMFoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=